integrated_block:
    resource: "@IntegratedBlockBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_page:
    resource: "@IntegratedPageBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_content:
    resource: "@IntegratedContentBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_channel:
    resource: "@IntegratedChannelBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_user:
    resource: "@IntegratedUserBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_security:
    resource: "@IntegratedUserBundle/Resources/config/routing.security.xml"
    prefix: "/admin"

integrated_website:
    resource: "@IntegratedWebsiteBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
